### ISSUE TITLE
Application not working

### ISSUE THREAD

**Issue by lalitkashyap58** [haddercone/Namaste-React#7]

**Comment by haddercone** [comment]
Hey @lalitkashyap58, thanks for the issue.
The application failure is due to recent Swiggy API update.
You can find the fix for this [here](https://github.com/namastedev/namaste-react/commit/d3f0d801df96fb40a7d03cb411c72a469bbaef51).

File locations needed to be modified:
https://github.com/haddercone/Namaste-React/blob/6b9fea448b37d38d82073871c2d34100efd385de/Session-12/code/src/components/RestrauntCard.js#L7-L15

https://github.com/haddercone/Namaste-React/blob/6b9fea448b37d38d82073871c2d34100efd385de/Session-12/code/src/utils/useRestaurantList.js#L13-L18

https://github.com/haddercone/Namaste-React/blob/6b9fea448b37d38d82073871c2d34100efd385de/Session-12/code/src/components/Body.js#L32-L39

I would really appropriate if you can raise the PR for this.

Thanks :)

**Comment by lalitkashyap58** [comment]
Hey ,I have fixed this issue but there is something more broken into the code ,probably the images below the header section
